# Generated by Django 2.1.7 on 2019-03-31 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('is_musician', models.BooleanField(default=False, verbose_name='Músico')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Móvil/Whatsapp')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='Correo')),
                ('facebook', models.CharField(blank=True, max_length=30, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=30, verbose_name='Twitter')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musi_find_backend.Genre', verbose_name='Genero principal')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musi_find_backend.Instrument', verbose_name='Instrumento principal')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Título')),
                ('content', models.CharField(max_length=300, verbose_name='Contenido')),
                ('publish_date', models.DateField()),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musi_find_backend.Profile', verbose_name='Publicante')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater', models.IntegerField(verbose_name='Calificante')),
                ('score', models.FloatField()),
                ('rated', models.ForeignKey(on_delete='Calificador', to='musi_find_backend.Profile')),
            ],
        ),
    ]
