# Generated by Django 2.1.7 on 2019-04-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musi_find_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField(blank=True, null=True, verbose_name='Emisor')),
                ('recipient_id', models.IntegerField(blank=True, null=True, verbose_name='Receptor')),
                ('time_sent', models.TimeField(blank=True, null=True, verbose_name='Hora emision')),
                ('content', models.CharField(max_length=500, verbose_name='Contenido')),
                ('seen', models.BooleanField(default=False, verbose_name='Visto')),
            ],
        ),
    ]
