# Generated by Django 2.1.7 on 2019-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musi_find_backend', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.IntegerField(blank=True, null=True, verbose_name='Baneador')),
                ('banned', models.IntegerField(blank=True, null=True, verbose_name='Baneado')),
            ],
        ),
    ]
