# Generated by Django 2.1.7 on 2019-04-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musi_find_backend', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Seguidor'),
        ),
    ]
