# Generated by Django 2.1.7 on 2019-04-11 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musi_find_backend', '0003_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha hora de envio'),
        ),
    ]
