# Generated by Django 2.1.7 on 2019-04-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musi_find_backend', '0004_auto_20190402_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
