# Generated by Django 2.1.7 on 2019-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musi_find_backend', '0004_auto_20190411_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha hora de envio'),
        ),
    ]
