# Generated by Django 2.1.7 on 2019-04-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musi_find_backend', '0005_auto_20190402_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
